### PR TITLE
Updated main doc

### PR DESCRIPTION
**Pull request by jamesatjaminit**
Added images on steps 6,7 and 11.

### CODE REVIEW

**Comment by Mcharlsto** [comment]
Step 6 looks good. Can you enlarge step 7/base it off a larger image in project storage. Does step 11 really need an image? The battery isn't really in focus.

**Comment by Mcharlsto** [comment]
Also, step 12 could do with an image, one of the finished product?

**Comment by jamesatjaminit** [comment]
Okay, I'll add those now

**Comment by Mcharlsto** [comment]
Did you ever get this done? I need to merge the staging branch but this needs doing first.

**Comment by Mcharlsto** [comment]
Never mind just added step 6 to staging. Will be merged soon.

**Pull request closed without merging**
